# Generated by Django 4.1 on 2022-09-11 16:55

import API.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=API.models.generate_random_code, max_length=8, unique=True),
        ),
    ]
